// omnipath-svelte/src/lib/components/explore/RelationsExploreTab.svelte
<script lang="ts">
  import { Filter, Minus, X } from '@lucide/svelte';
  import { Badge } from '$lib/components/ui/badge/index.js';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Alert, AlertDescription } from '$lib/components/ui/alert/index.js';
  import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '$lib/components/ui/sheet/index.js';
  import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '$lib/components/ui/table/index.js';
  import EntityBadge from '$lib/components/entity/EntityBadge.svelte';
  import InteractionFilterSidebar from '$lib/components/interactions/InteractionFilterSidebar.svelte';
  import InteractionDetailsSheet from '$lib/components/interactions/InteractionDetailsSheet.svelte';
  import { IsMobile } from '$lib/hooks/is-mobile.svelte';
  import { fetchRelationsSearch, fetchEntitiesByPks } from '$lib/api/client';
  import {
    getEntityDisplayName,
    getEntityPublicId,
    getEntitySecondaryName,
    getEntityTypeLabel,
  } from '$lib/entities/display';
  import type { SearchFilters } from '$lib/types/search';
  import type { InteractionListRow } from '$lib/types/interactions';
  import { formatNumber } from '$lib/utils/format';

  interface Props {
    filters: SearchFilters;
    onFilterChange: (filters: SearchFilters) => void;
    scopedEntityIds?: string[];
    scopedAnnotationIds?: string[];
  }

  let { filters, onFilterChange, scopedEntityIds, scopedAnnotationIds }: Props = $props();

  const isMobile = new IsMobile();
  const RESULTS_PER_PAGE = 20;

  let results = $state<InteractionListRow[]>([]);
  let loading = $state(false);
  let loadingMore = $state(false);
  let hasMore = $state(true);
  let offset = $state(0);
  let error = $state<string | null>(null);
  let selectedInteraction = $state<InteractionListRow | null>(null);
  let detailsOpen = $state(false);

  const activeFilterCount = $derived(
    Object.entries(filters).reduce((count, [, value]) => {
      if (Array.isArray(value)) return count + value.length;
      if (value !== null && value !== undefined) return count + 1;
      return count;
    }, 0)
  );

  const effectiveFilters = $derived({
    ...filters,
    ...(scopedEntityIds && scopedEntityIds.length > 0 ? { scope_entity_ids: scopedEntityIds } : {}),
    ...(scopedAnnotationIds && scopedAnnotationIds.length > 0 ? { scope_annotation_ids: scopedAnnotationIds } : {}),
  });

  // Reactive reset: only read external dependencies in the effect body.
  // Capture them into local consts, reset internal state, then fetch.
  $effect(() => {
    const f = effectiveFilters;

    results = [];
    offset = 0;
    hasMore = true;
    loading = true;
    error = null;

    (async () => {
      try {
        const data = await fetchRelationsSearch({ filters: f, limit: RESULTS_PER_PAGE, offset: 0 });

        const entityPksToHydrate = Array.from(
          new Set(data.relations.flatMap((r) => [r.subjectEntityPk, r.objectEntityPk]))
        );
        const entityData = entityPksToHydrate.length > 0
          ? await fetchEntitiesByPks(entityPksToHydrate)
          : { entities: [] };
        const entityByPk = new Map(entityData.entities.map((e) => [e.entityPk, e]));

        const hits = data.relations.flatMap((relation) => {
          const subjectEntity = entityByPk.get(relation.subjectEntityPk);
          const objectEntity = entityByPk.get(relation.objectEntityPk);
          if (!subjectEntity || !objectEntity) return [];
          return [{ relation, subjectEntity, objectEntity }];
        });

        results = hits;
        hasMore = hits.length === RESULTS_PER_PAGE;
        offset = RESULTS_PER_PAGE;
      } catch (err) {
        error = err instanceof Error ? err.message : 'Failed to load relations';
        hasMore = false;
      } finally {
        loading = false;
      }
    })();
  });

  async function loadMore() {
    if (loadingMore || !hasMore) return;
    loadingMore = true;
    try {
      const data = await fetchRelationsSearch({
        filters: effectiveFilters,
        limit: RESULTS_PER_PAGE,
        offset,
      });

      const entityPksToHydrate = Array.from(
        new Set(data.relations.flatMap((r) => [r.subjectEntityPk, r.objectEntityPk]))
      );
      const entityData = entityPksToHydrate.length > 0
        ? await fetchEntitiesByPks(entityPksToHydrate)
        : { entities: [] };
      const entityByPk = new Map(entityData.entities.map((e) => [e.entityPk, e]));

      const hits = data.relations.flatMap((relation) => {
        const subjectEntity = entityByPk.get(relation.subjectEntityPk);
        const objectEntity = entityByPk.get(relation.objectEntityPk);
        if (!subjectEntity || !objectEntity) return [];
        return [{ relation, subjectEntity, objectEntity }];
      });

      results = [...results, ...hits];
      hasMore = hits.length === RESULTS_PER_PAGE;
      offset += RESULTS_PER_PAGE;
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to load more relations';
    } finally {
      loadingMore = false;
    }
  }

  function handleClearFilters() {
    onFilterChange({ relation_categories: ['interaction'] });
  }

  function handleRowClick(row: InteractionListRow) {
    selectedInteraction = row;
    detailsOpen = true;
  }
</script>

{#snippet searchPanel()}
  <div class="relative h-full overflow-hidden">
    {#if isMobile.current}
      <div class="lg:hidden p-4 border-b">
        <Sheet>
          <SheetTrigger>
            <Button variant="outline" class="w-full">
              <Filter class="h-4 w-4 mr-2" />
              Filters
              {#if activeFilterCount > 0}
                <Badge variant="secondary" class="ml-2">
                  {activeFilterCount}
                </Badge>
              {/if}
            </Button>
          </SheetTrigger>
          <SheetContent side="left" class="w-[85%] sm:w-[400px] p-0">
            <SheetHeader class="px-6 py-4 border-b">
              <div class="flex items-center justify-between">
                <SheetTitle class="flex items-center gap-2">
                  <Filter class="h-5 w-5 text-primary" />
                  Filters
                </SheetTitle>
                {#if activeFilterCount > 0}
                  <Button
                    variant="ghost"
                    size="sm"
                    onclick={handleClearFilters}
                    class="flex items-center gap-1 text-muted-foreground hover:text-foreground"
                  >
                    <X class="h-4 w-4" />
                    Clear all
                  </Button>
                {/if}
              </div>
            </SheetHeader>
            <div class="h-[calc(100%-4rem)] overflow-y-auto">
              <InteractionFilterSidebar
                filters={effectiveFilters}
                onFilterChange={onFilterChange}
                onClearFilters={handleClearFilters}
                isMobile
              />
            </div>
          </SheetContent>
        </Sheet>
      </div>
    {/if}

    {#if error}
      <div class="p-6">
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      </div>
    {:else if loading && results.length === 0}
      <div class="flex items-center justify-center h-full">
        <div class="flex items-center gap-2">
          <div class="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent"></div>
          <span class="text-sm text-muted-foreground">Loading relations...</span>
        </div>
      </div>
    {:else if results.length > 0}
      <div class="flex flex-col h-full">
        <!-- Fixed Table Header -->
        <div class="relative border-b bg-background px-3 h-[57px] flex items-center flex-shrink-0">
          <Table class="pr-28">
            <TableHeader>
              <TableRow>
                <TableHead class="w-[35%] py-2">Source</TableHead>
                <TableHead class="w-[50px] text-center py-2">Predicate</TableHead>
                <TableHead class="w-[35%] py-2">Target</TableHead>
                <TableHead class="w-[20%] text-center py-2 pr-28">Evidence</TableHead>
              </TableRow>
            </TableHeader>
          </Table>
        </div>

        <!-- Scrollable Table Body -->
        <div class="flex-1 min-h-0 overflow-y-auto">
          <Table>
            <TableBody>
              {#each results as row}
                {@const sourceEntity = row.subjectEntity}
                {@const targetEntity = row.objectEntity}
                {@const sourceId = getEntityPublicId(sourceEntity)}
                {@const targetId = getEntityPublicId(targetEntity)}
                <TableRow
                  onclick={() => handleRowClick(row)}
                  class="cursor-pointer hover:bg-muted/50"
                >
                  <TableCell class="w-[35%] max-w-0">
                    <EntityBadge
                      displayName={getEntityDisplayName(sourceEntity)}
                      canonicalIdentifier={getEntitySecondaryName(sourceEntity) || sourceEntity.canonicalIdentifier}
                      entityType={getEntityTypeLabel(sourceEntity)}
                    />
                  </TableCell>
                  <TableCell class="w-[50px] text-center">
                    <div class="flex justify-center">
                      {#if row.relation.predicate.trim()}
                        <span class="text-sm text-muted-foreground">{row.relation.predicate}</span>
                      {:else}
                        <Minus class="h-4 w-4 text-muted-foreground" />
                      {/if}
                    </div>
                  </TableCell>
                  <TableCell class="w-[35%] max-w-0">
                    <EntityBadge
                      displayName={getEntityDisplayName(targetEntity)}
                      canonicalIdentifier={getEntitySecondaryName(targetEntity) || targetEntity.canonicalIdentifier}
                      entityType={getEntityTypeLabel(targetEntity)}
                    />
                  </TableCell>
                  <TableCell class="w-[20%] text-center">
                    <Badge variant="outline">
                      {formatNumber(row.relation.evidenceCount || 0)}
                    </Badge>
                  </TableCell>
                </TableRow>
              {/each}
              {#if hasMore}
                <TableRow>
                  <TableCell colspan={4} class="p-0">
                    <div class="flex justify-center py-4" style="min-height: 40px;">
                      <Button variant="outline" onclick={loadMore} disabled={loadingMore}>
                        {#if loadingMore}
                          <div class="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent mr-2"></div>
                          <span>Loading...</span>
                        {:else}
                          <span>Load more</span>
                        {/if}
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              {/if}
            </TableBody>
          </Table>
        </div>
      </div>
    {:else if !loading && results.length === 0}
      <div class="p-6 flex-1 flex items-center justify-center">
        <p class="text-muted-foreground text-center">
          {Object.keys(effectiveFilters).length > 0
            ? "No relations found matching your criteria."
            : "Select filters to explore relations."}
        </p>
      </div>
    {/if}
  </div>
{/snippet}

{#snippet desktopSidebar()}
  <div class="h-full min-h-[60vh] overflow-hidden rounded-2xl border bg-background/30">
    <div class="flex h-full">
      <div class="min-h-0 flex-1 overflow-hidden">
        {@render searchPanel()}
      </div>
      <div class="w-72 border-l bg-background/40 overflow-y-auto">
        <InteractionFilterSidebar
          filters={effectiveFilters}
          onFilterChange={onFilterChange}
          onClearFilters={handleClearFilters}
        />
      </div>
    </div>
  </div>
{/snippet}

<div class="relative flex flex-col overflow-hidden h-full min-h-0">
  <div class="flex-1 min-h-0">
    {#if isMobile.current}
      {@render searchPanel()}
    {:else}
      {@render desktopSidebar()}
    {/if}
  </div>

  <!-- Interaction Details Sheet -->
  <InteractionDetailsSheet
    open={detailsOpen}
    onOpenChange={(open) => { detailsOpen = open; }}
    interaction={selectedInteraction}
  />
</div>

// next-omnipath/src/features/explore/components/relations-explore-tab.tsx
"use client";

import { EntityBadge } from "@/components/entity-badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { InteractionListRow } from "@/features/interactions-search/types";
import {
  getEntityDisplayName,
  getEntityPublicId,
  getEntitySecondaryName,
  getEntityTypeLabel,
} from "@/lib/entities/display";
import { getEntitiesByPks, getEntitiesByPublicIds } from "@/lib/queries/entity";
import { searchRelations } from "@/lib/queries/relation";
import { DataCard } from "@/features/interactions-search/components/data-card";
import { AnnotationFilterSidebar, FilterSidebar } from "@/features/interactions-search/components/filter-sidebar";
import { InteractionDetailsSheet } from "@/features/interactions-search/components/interaction-details-sheet";
import { useInfiniteScroll } from "@/hooks/use-infinite-scroll";
import { useIsMobile } from "@/hooks/use-mobile";
import { cn, formatNumber } from "@/lib/utils";
import { SearchFilters } from "@/types/search";
import { Filter, Minus, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

const RESULTS_PER_PAGE = 20;

type ViewMode = "table" | "network";
type LayoutMode = "search" | "split" | "ontology";

interface RelationsExploreTabProps {
  filters: SearchFilters;
  onFilterChange: (filters: SearchFilters) => void;
  useInternalRefineLayout?: boolean;
  scopedEntityIds?: string[];
}

async function searchInteractionRows({
  filters,
  limit,
  offset,
}: {
  filters: SearchFilters;
  limit: number;
  offset: number;
}): Promise<{ hits: InteractionListRow[]; total: number }> {
  let entityPks: number[] | undefined;
  if (filters.entity_ids?.length) {
    const entities = await getEntitiesByPublicIds(filters.entity_ids.map(String));
    entityPks = entities.map((entity) => entity.entityPk);
    if (entityPks.length === 0) {
      return { hits: [], total: 0 };
    }
  }

  const relationCategories = Array.from(new Set([
    "interaction",
    ...(filters.relation_categories?.length ? filters.relation_categories : []),
  ])).filter((value) => value === "interaction");

  const { relations, total } = await searchRelations({
    filters: {
      relationCategories,
      entityPks,
      predicates: filters.predicates,
      sources: filters.sources,
    },
    limit,
    offset,
  });

  const entityPksToHydrate = Array.from(
    new Set(relations.flatMap((relation) => [relation.subjectEntityPk, relation.objectEntityPk])),
  );
  const entities = entityPksToHydrate.length > 0 ? await getEntitiesByPks(entityPksToHydrate) : [];
  const entityByPk = new Map(entities.map((entity) => [entity.entityPk, entity]));

  const hits = relations.flatMap((relation) => {
    const subjectEntity = entityByPk.get(relation.subjectEntityPk);
    const objectEntity = entityByPk.get(relation.objectEntityPk);
    if (!subjectEntity || !objectEntity) return [];
    return [{ relation, subjectEntity, objectEntity }];
  });

  return { hits, total };
}

export function RelationsExploreTab({
  filters,
  onFilterChange,
  useInternalRefineLayout = true,
  scopedEntityIds,
}: RelationsExploreTabProps) {
  const mainContentRef = useRef<HTMLDivElement | null>(null);
  const isMobile = useIsMobile();
  const [rootElement, setRootElement] = useState<HTMLDivElement | null>(null);
  const [error, setError] = useState<string | null>(null);
  const effectiveFilters = useMemo<SearchFilters>(() => ({
    ...filters,
    ...(scopedEntityIds && scopedEntityIds.length > 0
      ? {
          entity_ids: scopedEntityIds,
          member_a_id: undefined,
          member_b_id: undefined,
        }
      : {}),
  }), [filters, scopedEntityIds]);

  // Infinite scroll hook
  const {
    data: results,
    loading,
    loadingMore,
    hasMore,
    error: infiniteScrollError,
    totalResults,
    sentinelRef
  } = useInfiniteScroll<InteractionListRow>({
    fetchData: useCallback(async (offset: number, limit: number) => {
      const response = await searchInteractionRows({ filters: effectiveFilters, limit, offset });

      return {
        results: response.hits,
        totalResults: response.total,
      };
    }, [effectiveFilters]),
    pageSize: RESULTS_PER_PAGE,
    dependencies: [effectiveFilters],
    root: rootElement
  });

  const [selectedInteraction, setSelectedInteraction] = useState<InteractionListRow | null>(null);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [viewMode, setViewMode] = useState<ViewMode>("table");
  const [layoutMode, setLayoutMode] = useState<LayoutMode>("search");

  // Ontology browser is always available for searching terms
  const hasOntologyTerms = true;

  // Update error state from infinite scroll hook
  useEffect(() => {
    setError(infiniteScrollError?.message || null);
  }, [infiniteScrollError]);

  // Handler for clear filters
  const handleClearFilters = () => {
    onFilterChange(scopedEntityIds && scopedEntityIds.length > 0 ? { entity_ids: scopedEntityIds, relation_categories: ["interaction"] } : { relation_categories: ["interaction"] });
  };

  const handleRowClick = (row: InteractionListRow) => {
    setSelectedInteraction(row);
    setDetailsOpen(true);
  };

  // Handle export
  const handleExport = useCallback(async () => {
    try {
      setError(null);
      const date = new Date().toISOString().split('T')[0];
      const response = await fetch('/api/exports/interactions/parquet', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: '',
          filters: effectiveFilters,
          filename: `relations_subset_${date}`,
        }),
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        throw new Error(payload.error || `Export failed (${response.status})`);
      }

      const blob = await response.blob();
      const downloadUrl = window.URL.createObjectURL(blob);
      const contentDisposition = response.headers.get('Content-Disposition');
      const fileNameMatch = contentDisposition?.match(/filename="?([^";]+)"?/i);
      const fileName = fileNameMatch?.[1] || `relations_subset_${date}.parquet`;

      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(downloadUrl);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to export relations');
    }
  }, [effectiveFilters]);

  const renderPredicate = (row: InteractionListRow) => {
    if (row.relation.predicate.trim()) {
      return <span className="text-sm text-muted-foreground">{row.relation.predicate}</span>;
    }
    return <Minus className="h-4 w-4 text-muted-foreground" />;
  };

  const searchPanel = (
    <div className="h-full overflow-hidden p-4">
      <DataCard
        className={cn("h-full min-w-0 flex flex-col")}
        title={`${formatNumber(totalResults)} relations found`}
        viewMode={viewMode}
        onViewModeChange={setViewMode}
        onExport={handleExport}
      >
        {/* Mobile filter drawer */}
        <div className="lg:hidden p-4 border-b">
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="outline" className="w-full">
                <Filter className="h-4 w-4 mr-2" />
                Filters
                {Object.keys(filters).length > 0 && (
                  <Badge variant="secondary" className="ml-2">
                    {Object.entries(filters).reduce((count, [, value]) => {
                      if (Array.isArray(value)) return count + value.length;
                      if (value !== null && value !== undefined) return count + 1;
                      return count;
                    }, 0)}
                  </Badge>
                )}
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-[85%] sm:w-[400px] p-0">
              <SheetHeader className="px-6 py-4 border-b">
                <div className="flex items-center justify-between">
                  <SheetTitle className="flex items-center gap-2">
                    <Filter className="h-5 w-5 text-primary" />
                    Filters
                  </SheetTitle>
                  {Object.keys(filters).length > 0 && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleClearFilters}
                      className="flex items-center gap-1 text-muted-foreground hover:text-foreground"
                    >
                      <X className="h-4 w-4" />
                      Clear all
                    </Button>
                  )}
                </div>
              </SheetHeader>
              <div className="h-[calc(100%-4rem)] overflow-y-auto">
                <FilterSidebar
                  filters={effectiveFilters}
                  onFilterChange={onFilterChange}
                  onClearFilters={handleClearFilters}
                  isMobile
                />
              </div>
            </SheetContent>
          </Sheet>
        </div>

        {/* Results */}
        {viewMode === "table" ? (
          error ? (
            <div className="p-6">
              <Alert variant="destructive">
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            </div>
          ) : results.length > 0 ? (
            <div className="flex flex-col h-full">
              {/* Fixed Table Header */}
              <div className="border-b bg-background px-3 h-[57px] flex items-center flex-shrink-0">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[35%] py-2">Source</TableHead>
                      <TableHead className="w-[50px] text-center py-2">Predicate</TableHead>
                      <TableHead className="w-[35%] py-2">Target</TableHead>
                      <TableHead className="w-[20%] text-center py-2">Evidence</TableHead>
                    </TableRow>
                  </TableHeader>
                </Table>
              </div>

              {/* Scrollable Table Body */}
              <div
                ref={(el) => {
                  mainContentRef.current = el;
                  setRootElement(el);
                }}
                className="flex-1 min-h-0 overflow-y-auto"
              >
                <Table>
                  <TableBody>
                    {results.map((row) => {
                      const sourceEntity = row.subjectEntity;
                      const targetEntity = row.objectEntity;
                      const sourceId = getEntityPublicId(sourceEntity);
                      const targetId = getEntityPublicId(targetEntity);

                      return (
                        <TableRow
                          key={String(row.relation.relationPk)}
                          onClick={() => handleRowClick(row)}
                          className="cursor-pointer hover:bg-muted/50"
                        >
                          <TableCell className="w-[35%] max-w-0">
                            <EntityBadge
                              displayName={getEntityDisplayName(sourceEntity)}
                              canonicalIdentifier={getEntitySecondaryName(sourceEntity) || sourceEntity.canonicalIdentifier}
                              entityId={sourceId}
                              entityType={getEntityTypeLabel(sourceEntity)}
                            />
                          </TableCell>
                          <TableCell className="w-[50px] text-center">
                            <div className="flex justify-center">
                              {renderPredicate(row)}
                            </div>
                          </TableCell>
                          <TableCell className="w-[35%] max-w-0">
                            <EntityBadge
                              displayName={getEntityDisplayName(targetEntity)}
                              canonicalIdentifier={getEntitySecondaryName(targetEntity) || targetEntity.canonicalIdentifier}
                              entityId={targetId}
                              entityType={getEntityTypeLabel(targetEntity)}
                            />
                          </TableCell>
                          <TableCell className="w-[20%] text-center">
                            <Badge variant="outline">
                              {formatNumber(row.relation.evidenceCount || 0)}
                            </Badge>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                    {/* Infinite scroll trigger */}
                    <TableRow style={{ display: hasMore ? 'table-row' : 'none' }}>
                      <TableCell colSpan={4} className="p-0">
                        <div
                          ref={sentinelRef as React.RefObject<HTMLDivElement>}
                          className="flex justify-center py-4"
                          style={{ minHeight: '40px' }}
                        >
                          {loadingMore ? (
                            <div className="flex items-center gap-2">
                              <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
                              <span className="text-sm text-muted-foreground">Loading more...</span>
                            </div>
                          ) : (
                            <div className="h-4 w-4" />
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

              </div>
            </div>
          ) : !loading && (
            <div className="p-6 flex-1 flex items-center justify-center">
              <p className="text-muted-foreground text-center">
                {Object.keys(filters).length > 0
                  ? "No relations found matching your criteria."
                  : "Loading relations..."}
              </p>
            </div>
          )
        )  : null}
      </DataCard>
    </div>
  );

  const ontologyPanel = (
    <div className="h-full min-h-0 overflow-hidden p-4">
      <div className="h-full overflow-y-auto">
        <AnnotationFilterSidebar
          mode="interactions"
          filters={effectiveFilters}
          onFilterChange={onFilterChange}
        />
      </div>
    </div>
  );

  return (
    <div
      className={cn(
        "relative flex flex-col overflow-hidden",
        useInternalRefineLayout ? "h-svh" : "h-full min-h-0",
      )}
    >
      <div className="flex-1 min-h-0">
        {!useInternalRefineLayout ? (
          isMobile ? (
            searchPanel
          ) : (
            <div className="h-full min-h-[60vh] overflow-hidden rounded-2xl border bg-background/30">
              <ResizablePanelGroup direction="horizontal" className="h-full">
                <ResizablePanel defaultSize={72} minSize={45} className="min-h-0 overflow-hidden">
                  {searchPanel}
                </ResizablePanel>
                <ResizableHandle withHandle />
                <ResizablePanel defaultSize={28} minSize={22} className="min-h-0 border-l bg-background/40">
                  <div className="h-full overflow-y-auto p-4">
                    <FilterSidebar
                      filters={effectiveFilters}
                      onFilterChange={onFilterChange}
                      onClearFilters={handleClearFilters}
                    />
                  </div>
                </ResizablePanel>
              </ResizablePanelGroup>
            </div>
          )
        ) : layoutMode === "split" && hasOntologyTerms ? (
          <ResizablePanelGroup direction="horizontal" className="h-full">
            <ResizablePanel defaultSize={68} minSize={50} className="min-h-0">
              {searchPanel}
            </ResizablePanel>
            <ResizableHandle withHandle className="mx-3" />
            <ResizablePanel defaultSize={32} minSize={25} className="min-h-0">
              {ontologyPanel}
            </ResizablePanel>
          </ResizablePanelGroup>
        ) : layoutMode === "ontology" && hasOntologyTerms ? (
          ontologyPanel
        ) : (
          searchPanel
        )}
      </div>

      {/* Interaction Details Sheet */}
      <InteractionDetailsSheet
        open={detailsOpen}
        onOpenChange={setDetailsOpen}
        interaction={selectedInteraction}
      />

      {/* Layout mode switcher - only show if refine content is available */}
      {useInternalRefineLayout && hasOntologyTerms && (
        <div className="fixed bottom-4 right-4 z-40">
          <div className="inline-flex items-center rounded-full border bg-background/90 p-1 shadow-sm">
            <Button
              size="sm"
              variant={layoutMode === "search" ? "default" : "ghost"}
              onClick={() => setLayoutMode("search")}
              className="rounded-full h-8"
            >
              Results
            </Button>
            <Button
              size="sm"
              variant={layoutMode === "split" ? "default" : "ghost"}
              onClick={() => setLayoutMode("split")}
              className="rounded-full h-8"
            >
              Both
            </Button>
            <Button
              size="sm"
              variant={layoutMode === "ontology" ? "default" : "ghost"}
              onClick={() => setLayoutMode("ontology")}
              className="rounded-full h-8"
            >
              Refine
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
