// omnipath-svelte/src/routes/resources/+page.svelte
<script lang="ts">
	import { ChevronDown, ChevronUp, Database, Download, ExternalLink, Layers3, Network, Search, Tags } from '@lucide/svelte';
	import { toast } from 'svelte-sonner';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Tabs, TabsList, TabsTrigger } from '$lib/components/ui/tabs/index.js';
	import { cn } from '$lib/utils.js';
	import type { ResourceRecord } from '$lib/server/resource';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	let query = $state('');
	let selectedCategory = $state('all');
	let expandedIds = $state<Set<string>>(new Set());
	let downloadingIds = $state<Set<string>>(new Set());

	const categories = [
		{ value: 'all', label: 'All' },
		{ value: 'annotation', label: 'Annotation' },
		{ value: 'interaction', label: 'Interaction' },
		{ value: 'membership', label: 'Membership' }
	] as const;

	const filteredResources = $derived.by(() => {
		const normalizedQuery = query.trim().toLowerCase();

		return data.resources.filter((resource) => {
			const searchableText = [
				resource.resource_name,
				resource.resource_id,
				resource.description,
				...(resource.categories || []),
				...(resource.annotation_ontologies || [])
			]
				.filter(Boolean)
				.join(' ')
				.toLowerCase();

			const matchesQuery = normalizedQuery.length === 0 || searchableText.includes(normalizedQuery);
			const matchesCategory =
				selectedCategory === 'all' ||
				resource.categories.includes(selectedCategory) ||
				(selectedCategory === 'membership' && resource.categories.includes('association'));

			return matchesQuery && matchesCategory;
		});
	});

	function sentenceCase(value: string | null | undefined): string {
		if (!value) return 'Unknown';
		return value.replace(/_/g, ' ').replace(/\b\w/g, (match) => match.toUpperCase());
	}

	function handleSubmitSearch() {
		query = query.trim();
	}

	function handleSearchKeyDown(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			event.preventDefault();
			handleSubmitSearch();
		}
	}

	function formatFileSize(bytes: number | null | undefined): string {
		const value = bytes || 0;
		if (value < 1024) return `${value} B`;

		const units = ['KB', 'MB', 'GB', 'TB'];
		let size = value / 1024;
		let unitIndex = 0;

		while (size >= 1024 && unitIndex < units.length - 1) {
			size /= 1024;
			unitIndex += 1;
		}

		return `${size.toFixed(size >= 10 ? 0 : 1)} ${units[unitIndex]}`;
	}

	function formatDate(value: string | null | undefined): string {
		if (!value) return '—';
		const date = new Date(value);
		if (Number.isNaN(date.getTime())) return value;

		return new Intl.DateTimeFormat('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric'
		}).format(date);
	}

	function iconForCategories(categories: string[]) {
		if (categories.includes('interaction')) return Network;
		if (categories.includes('annotation')) return Layers3;
		if (categories.includes('membership') || categories.includes('association')) return Tags;
		return Database;
	}

	function toggleExpanded(resourceId: string) {
		expandedIds = new Set(expandedIds).has(resourceId)
			? new Set([...expandedIds].filter((id) => id !== resourceId))
			: new Set(expandedIds).add(resourceId);
	}

	async function handleDownload(resource: ResourceRecord) {
		try {
			downloadingIds = new Set(downloadingIds).add(resource.resource_id);
			toast.info('Resource downloads will be wired to /app-api/resources/download in a follow-up milestone.');
		} finally {
			downloadingIds = new Set([...downloadingIds].filter((id) => id !== resource.resource_id));
		}
	}
</script>


<div class="relative mx-auto flex h-full min-h-0 w-full max-w-7xl flex-1 flex-col gap-4 overflow-hidden px-4 py-4 md:px-6 md:py-5">
	<div class="shrink-0 space-y-3">
		<div class="rounded-[1.4rem] border bg-card p-2.5 shadow-sm">
			<div class="flex flex-col gap-2.5 lg:flex-row lg:items-center">
				<div class="relative min-w-0 flex-1">
					<Search class="absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-muted-foreground" />
					<Input
						type="search"
						bind:value={query}
						onkeydown={handleSearchKeyDown}
						placeholder="Search resources…"
						class="h-11 rounded-[1rem] border-0 bg-muted/40 pl-10 text-sm shadow-none sm:text-base"
					/>
				</div>

				<div class="flex items-center gap-2 lg:shrink-0">
					<Button onclick={handleSubmitSearch} class="h-9 rounded-lg px-3.5 text-sm">Search</Button>
				</div>
			</div>

			<div class="mt-2.5 flex items-center justify-between gap-3">
				<Tabs value={selectedCategory} onValueChange={(value) => (selectedCategory = value)} class="min-w-0 flex-1">
					<TabsList class="grid h-auto w-full grid-cols-4 rounded-xl bg-muted/60 p-1">
						{#each categories as category}
							<TabsTrigger value={category.value} class="rounded-lg text-sm">
								{category.label}
							</TabsTrigger>
						{/each}
					</TabsList>
				</Tabs>
			</div>
		</div>
	</div>

	<div class="min-h-0 flex-1 overflow-y-auto pr-1">
		<section class="space-y-4">
			{#if filteredResources.length > 0}
					<div class="grid grid-cols-1 items-start gap-4 xl:grid-cols-2 2xl:grid-cols-3">
						{#each filteredResources as resource (resource.resource_id)}
							{@const expanded = expandedIds.has(resource.resource_id)}
							{@const downloading = downloadingIds.has(resource.resource_id)}
							{@const Icon = iconForCategories(resource.categories)}
							<article class="flex h-full flex-col rounded-[1.25rem] border border-border/50 bg-card/70 p-4 transition-all hover:bg-muted/[0.18]">
								<div class="flex items-start justify-between gap-3">
									<div class="flex min-w-0 items-start gap-3">
										<div class="rounded-xl border border-border/60 bg-muted/25 p-2.5">
											<Icon class="h-4 w-4 text-muted-foreground" />
										</div>
										<div class="min-w-0">
											<div class="truncate text-lg font-semibold tracking-tight">{resource.resource_name}</div>
										</div>
									</div>

									<span class={cn('shrink-0 rounded-full px-2.5 py-1 text-[11px] font-medium', resource.build_status === 'success' ? 'bg-secondary/15 text-secondary' : 'bg-muted text-muted-foreground')}>
										{sentenceCase(resource.build_status)}
									</span>
								</div>

								<div class="mt-3 flex flex-wrap gap-2">
									{#each resource.categories as category (`${resource.resource_id}-${category}`)}
										<span class="inline-flex items-center rounded-full border border-border/60 bg-muted/35 px-2.5 py-1 text-[11px] font-medium text-muted-foreground">{sentenceCase(category)}</span>
									{/each}
									{#if !expanded}
										{#each resource.annotation_ontologies.slice(0, 1) as ontology (`${resource.resource_id}-${ontology}`)}
											<span class="inline-flex items-center rounded-full border border-border/60 bg-muted/35 px-2.5 py-1 text-[11px] font-medium text-muted-foreground">{ontology}</span>
										{/each}
									{/if}
								</div>

								<div class="mt-3 rounded-xl bg-muted/18 px-3.5 py-3">
									<p class={cn('overflow-hidden text-sm leading-6 text-muted-foreground [display:-webkit-box] [-webkit-box-orient:vertical]', expanded ? '[-webkit-line-clamp:8]' : '[-webkit-line-clamp:2]')}>
										{resource.description || 'No description available.'}
									</p>
								</div>

								<div class="mt-auto flex flex-col pt-3">
									<div class="flex items-center justify-between gap-3 border-t border-border/50 pt-3">
										<button type="button" onclick={() => toggleExpanded(resource.resource_id)} class="inline-flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground">
											{#if expanded}
												Hide details <ChevronUp class="h-4 w-4" />
											{:else}
												More details <ChevronDown class="h-4 w-4" />
											{/if}
										</button>

										<Button class="rounded-full" variant="outline" size="sm" onclick={() => handleDownload(resource)} disabled={downloading || resource.build_status !== 'success'} title={resource.build_status !== 'success' ? 'No download available for this resource' : undefined}>
											<Download class="h-4 w-4" />
											{downloading ? 'Downloading…' : 'Download'}
										</Button>
									</div>

									{#if expanded}
										<div class="mt-3 space-y-3 border-t border-border/50 pt-3">
											{#if resource.annotation_ontologies.length > 0}
												<div class="flex flex-wrap gap-2">
													{#each resource.annotation_ontologies as ontology (`${resource.resource_id}-${ontology}`)}
														<span class="inline-flex items-center rounded-full border border-border/60 bg-muted/35 px-2.5 py-1 text-[11px] font-medium text-muted-foreground">{ontology}</span>
													{/each}
												</div>
											{/if}

											<dl class="grid gap-2 text-sm">
												<div class="flex items-start justify-between gap-4"><dt class="font-mono text-[10px] tracking-[0.14em] text-muted-foreground uppercase">Resource ID</dt><dd class="max-w-[65%] text-right font-mono break-words text-foreground/90">{resource.resource_id}</dd></div>
												<div class="flex items-start justify-between gap-4"><dt class="font-mono text-[10px] tracking-[0.14em] text-muted-foreground uppercase">License</dt><dd class="max-w-[65%] text-right break-words text-foreground/90">{resource.license || '—'}</dd></div>
												<div class="flex items-start justify-between gap-4"><dt class="font-mono text-[10px] tracking-[0.14em] text-muted-foreground uppercase">Last Downloaded</dt><dd class="text-right text-foreground/90">{formatDate(resource.last_downloaded_at)}</dd></div>
												<div class="flex items-start justify-between gap-4"><dt class="font-mono text-[10px] tracking-[0.14em] text-muted-foreground uppercase">Last Built</dt><dd class="text-right text-foreground/90">{formatDate(resource.last_built_at)}</dd></div>
												<div class="flex items-start justify-between gap-4"><dt class="font-mono text-[10px] tracking-[0.14em] text-muted-foreground uppercase">Snapshot Size</dt><dd class="text-right text-foreground/90">{formatFileSize(resource.total_size_bytes)}</dd></div>
											</dl>

											<div class="flex flex-wrap items-center gap-1">
												{#if resource.homepage_url}
													<a href={resource.homepage_url} target="_blank" rel="noreferrer" class="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground">Site <ExternalLink class="h-3.5 w-3.5" /></a>
												{/if}
												{#if resource.pubmed_id}
													<a href={`https://pubmed.ncbi.nlm.nih.gov/${resource.pubmed_id}/`} target="_blank" rel="noreferrer" class="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground">PMID <Tags class="h-3.5 w-3.5" /></a>
												{/if}
											</div>
										</div>
									{/if}
								</div>
							</article>
						{/each}
					</div>
				{:else}
					<div class="rounded-[1.25rem] border border-border/60 bg-card px-6 py-14 text-center text-muted-foreground shadow-sm">
						No resources matched the current search and filter settings.
					</div>
				{/if}
		</section>
	</div>
</div>

// next-omnipath/src/features/resources/page.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { ResourceRecord } from "@/lib/resources";
import { downloadResourceSelection } from "@/lib/resource-downloads";
import { cn, formatNumber } from "@/lib/utils";
import {
  Check,
  ChevronDown,
  ChevronUp,
  Copy,
  Database,
  Download,
  ExternalLink,
  Layers3,
  Network,
  Search,
  Tags,
} from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

interface ResourcesSummary {
  totalResources: number;
  totalEntities: number;
  totalInteractions: number;
  totalAssociations: number;
  totalAnnotations: number;
  totalIdentifiers: number;
  totalOntologyTerms: number;
  totalBytes: number;
  buildStatusCounts: Record<string, number>;
  categoryCounts: Record<string, number>;
}

function sentenceCase(value: string | null | undefined): string {
  if (!value) return "Unknown";
  return value.replace(/_/g, " ").replace(/\b\w/g, (match) => match.toUpperCase());
}

function formatFileSize(bytes: number | null | undefined): string {
  const value = bytes || 0;
  if (value < 1024) return `${value} B`;

  const units = ["KB", "MB", "GB", "TB"];
  let size = value / 1024;
  let unitIndex = 0;

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex += 1;
  }

  return `${size.toFixed(size >= 10 ? 0 : 1)} ${units[unitIndex]}`;
}

function formatDate(value: string | null | undefined): string {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(date);
}

function iconForCategories(categories: string[]) {
  if (categories.includes("interaction")) return Network;
  if (categories.includes("annotation")) return Layers3;
  if (categories.includes("association")) return Tags;
  return Database;
}

function Pill({
  active,
  children,
  onClick,
}: {
  active?: boolean;
  children: React.ReactNode;
  onClick?: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-full border px-3.5 py-2 text-sm transition-colors",
        active
          ? "border-primary bg-primary text-primary-foreground"
          : "border-border bg-background text-muted-foreground hover:bg-muted/50 hover:text-foreground",
      )}
    >
      {children}
    </button>
  );
}

function MiniTag({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center rounded-full border border-border/60 bg-muted/35 px-2.5 py-1 text-[11px] font-medium text-muted-foreground">
      {children}
    </span>
  );
}

function ResourceCard({
  resource,
  selected,
  onToggle,
}: {
  resource: ResourceRecord;
  selected: boolean;
  onToggle: () => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const Icon = iconForCategories(resource.categories);
  const stats = [
    { label: "Entities", value: resource.entity_count },
    { label: "Interactions", value: resource.interaction_count },
    { label: "Associations", value: resource.association_count },
    { label: "Annotations", value: resource.annotation_count },
    { label: "Ontology Terms", value: resource.ontology_term_count },
  ].filter((stat) => stat.value > 0);
  const canDownloadArchive = resource.build_status === "success" && resource.download_archive_exists;

  return (
    <article
      className={cn(
        "flex h-full flex-col rounded-[1.25rem] border bg-card/70 p-4 transition-all",
        selected ? "border-primary/60 bg-primary/[0.04] ring-1 ring-primary/20" : "border-border/50 hover:bg-muted/[0.18]",
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-start gap-3">
          <div className="rounded-xl border border-border/60 bg-muted/25 p-2.5">
            <Icon className="h-4 w-4 text-muted-foreground" />
          </div>
          <div className="min-w-0">
            <div className="truncate text-lg font-semibold tracking-tight">{resource.resource_name}</div>
          </div>
        </div>

        <span
          className={cn(
            "shrink-0 rounded-full px-2.5 py-1 text-[11px] font-medium",
            resource.build_status === "success"
              ? "bg-secondary/15 text-secondary"
              : "bg-muted text-muted-foreground",
          )}
        >
          {sentenceCase(resource.build_status)}
        </span>
      </div>

      <div className="mt-3 flex flex-wrap gap-2">
        {resource.categories.map((category) => (
          <MiniTag key={`${resource.resource_id}-${category}`}>{sentenceCase(category)}</MiniTag>
        ))}
        {!expanded && resource.annotation_ontologies.slice(0, 1).map((ontology) => (
          <MiniTag key={`${resource.resource_id}-${ontology}`}>{ontology}</MiniTag>
        ))}
      </div>

      <div className="mt-3 rounded-xl bg-muted/18 px-3.5 py-3">
        <p
          className={cn(
            "text-sm leading-6 text-muted-foreground [display:-webkit-box] [-webkit-box-orient:vertical] overflow-hidden",
            expanded ? "[-webkit-line-clamp:8]" : "[-webkit-line-clamp:2]",
          )}
        >
          {resource.description || "No description available."}
        </p>
      </div>

      <div className="mt-auto flex flex-col pt-3">
        <div className="flex items-center justify-between gap-3 border-t border-border/50 pt-3">
          <button
            type="button"
            onClick={() => setExpanded((current) => !current)}
            className="inline-flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground"
          >
            {expanded ? (
              <>
                Hide details
                <ChevronUp className="h-4 w-4" />
              </>
            ) : (
              <>
                More details
                <ChevronDown className="h-4 w-4" />
              </>
            )}
          </button>

          {canDownloadArchive ? (
            <Button asChild className="rounded-full">
              <a href={`/api/resources/${encodeURIComponent(resource.resource_id)}/download`}>
                Download
                <Download className="h-4 w-4" />
              </a>
            </Button>
          ) : (
            <Button className="rounded-full" variant="outline" disabled>
              Download
              <Download className="h-4 w-4" />
            </Button>
          )}
        </div>

        {expanded ? (
          <div className="mt-3 space-y-3 border-t border-border/50 pt-3">
            {resource.annotation_ontologies.length > 0 ? (
              <div className="flex flex-wrap gap-2">
                {resource.annotation_ontologies.map((ontology) => (
                  <MiniTag key={`${resource.resource_id}-${ontology}`}>{ontology}</MiniTag>
                ))}
              </div>
            ) : null}

            {stats.length > 0 ? (
              <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">
                {stats.map((stat) => (
                  <div key={`${resource.resource_id}-${stat.label}`} className="rounded-lg bg-muted/15 px-3 py-2">
                    <div className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{stat.label}</div>
                    <div className="mt-1 text-sm font-semibold">{formatNumber(stat.value)}</div>
                  </div>
                ))}
              </div>
            ) : null}

            <dl className="grid gap-2 text-sm">
              <div className="flex items-start justify-between gap-4">
                <dt className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Resource ID</dt>
                <dd className="max-w-[65%] text-right font-mono text-foreground/90 break-words">{resource.resource_id}</dd>
              </div>
              <div className="flex items-start justify-between gap-4">
                <dt className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">License</dt>
                <dd className="max-w-[65%] text-right text-foreground/90 break-words">{resource.license || "—"}</dd>
              </div>
              <div className="flex items-start justify-between gap-4">
                <dt className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Last Built</dt>
                <dd className="text-right text-foreground/90">{formatDate(resource.last_built_at)}</dd>
              </div>
              <div className="flex items-start justify-between gap-4">
                <dt className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Snapshot Size</dt>
                <dd className="text-right text-foreground/90">{formatFileSize(resource.total_size_bytes)}</dd>
              </div>
              <div className="flex items-start justify-between gap-4">
                <dt className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Download Size</dt>
                <dd className="text-right text-foreground/90">{formatFileSize(resource.download_archive_size_bytes)}</dd>
              </div>
            </dl>

            <div className="flex flex-wrap items-center gap-1">
              {resource.homepage_url ? (
                <Link
                  href={resource.homepage_url}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground"
                >
                  Site
                  <ExternalLink className="h-3.5 w-3.5" />
                </Link>
              ) : null}
              {resource.pubmed_id ? (
                <Link
                  href={`https://pubmed.ncbi.nlm.nih.gov/${resource.pubmed_id}/`}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground"
                >
                  PMID
                  <Tags className="h-3.5 w-3.5" />
                </Link>
              ) : null}
            </div>
          </div>
        ) : null}
      </div>
    </article>
  );
}

export default function ResourcesPage({
  resources,
  summary,
}: {
  resources: ResourceRecord[];
  summary: ResourcesSummary;
}) {
  const [query, setQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);
  const [downloadingSelection, setDownloadingSelection] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const categories = useMemo(
    () => ["all", ...Object.keys(summary.categoryCounts).sort((a, b) => a.localeCompare(b))],
    [summary.categoryCounts],
  );

  const filteredResources = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();

    return resources.filter((resource) => {
      const searchableText = [
        resource.resource_name,
        resource.resource_id,
        resource.description,
        ...(resource.categories || []),
        ...(resource.annotation_ontologies || []),
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();

      const matchesQuery = normalizedQuery.length === 0 || searchableText.includes(normalizedQuery);
      const matchesCategory = selectedCategory === "all" || resource.categories.includes(selectedCategory);

      return matchesQuery && matchesCategory;
    });
  }, [query, resources, selectedCategory]);

  const selectedResources = useMemo(
    () => resources.filter((resource) => selectedIds.includes(resource.resource_id)),
    [resources, selectedIds],
  );

  const selectedTotalBytes = useMemo(
    () => selectedResources.reduce((sum, item) => sum + (item.total_size_bytes || 0), 0),
    [selectedResources],
  );

  function toggleSelected(resourceId: string) {
    setSelectedIds((current) =>
      current.includes(resourceId) ? current.filter((id) => id !== resourceId) : [...current, resourceId],
    );
  }

  async function copySelectedIds() {
    if (selectedIds.length === 0) return;
    await navigator.clipboard.writeText(selectedIds.join(","));
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  }

  async function handleSelectionDownload() {
    if (selectedIds.length === 0) return;

    try {
      setDownloadError(null);
      setDownloadingSelection(true);
      await downloadResourceSelection(selectedIds);
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : "Download failed.");
    } finally {
      setDownloadingSelection(false);
    }
  }

  return (
    <div className="relative mx-auto flex h-full min-h-0 w-full max-w-7xl flex-1 flex-col px-4 py-4 md:px-6 md:py-5">
      <div className="min-h-0 flex-1 overflow-y-auto pb-32 pr-1">
        <div className="space-y-4">
          <div className="rounded-[1.4rem] border bg-card p-3 shadow-sm">
            <div className="flex flex-col gap-3">
              <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
                <div className="min-w-0 flex-1">
                  <div className="text-xl font-semibold tracking-tight">Resource catalog</div>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Browse curated OmniPath resources and open focused local workspaces.
                  </p>
                </div>

                <div className="relative w-full xl:max-w-xl">
                  <Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    value={query}
                    onChange={(event) => setQuery(event.target.value)}
                    placeholder="Search resources, IDs, categories, or ontologies…"
                    className="h-11 rounded-[1rem] border-0 bg-muted/40 pl-10 text-sm shadow-none sm:text-base"
                  />
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                {categories.map((category) => (
                  <Pill key={category} active={selectedCategory === category} onClick={() => setSelectedCategory(category)}>
                    {category === "all" ? "All categories" : sentenceCase(category)}
                  </Pill>
                ))}
              </div>

              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 px-1 text-sm text-muted-foreground">
                <span>{formatNumber(summary.totalResources)} resources</span>
                <span>•</span>
                <span>{formatNumber(summary.totalEntities)} entities</span>
                <span>•</span>
                <span>{formatNumber(summary.totalInteractions)} interactions</span>
                <span>•</span>
                <span>{formatNumber(summary.totalAnnotations)} annotations</span>
              </div>
            </div>
          </div>

          <section className="space-y-4">
            <div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="text-sm text-muted-foreground">
                  Showing {filteredResources.length} of {resources.length} resources.
                </p>
              </div>
              <div className="text-sm text-muted-foreground">
                {formatNumber(summary.totalOntologyTerms)} ontology terms • {formatFileSize(summary.totalBytes)} total size
              </div>
            </div>

            {filteredResources.length > 0 ? (
              <div className="grid grid-cols-1 items-start gap-4 xl:grid-cols-2 2xl:grid-cols-3">
                {filteredResources.map((resource) => (
                  <ResourceCard
                    key={resource.resource_id}
                    resource={resource}
                    selected={selectedIds.includes(resource.resource_id)}
                    onToggle={() => toggleSelected(resource.resource_id)}
                  />
                ))}
              </div>
            ) : (
              <div className="rounded-[1.25rem] border border-border/60 bg-card px-6 py-14 text-center text-muted-foreground shadow-sm">
                No resources matched the current search and filter settings.
              </div>
            )}
          </section>
        </div>
      </div>

      {selectedResources.length > 0 ? (
        <div className="fixed inset-x-4 bottom-4 z-40">
          <div className="mx-auto w-full max-w-7xl rounded-[1.25rem] border border-border bg-background/95 shadow-lg backdrop-blur supports-[backdrop-filter]:bg-background/80">
            <div className="flex flex-col gap-4 px-4 py-4 sm:px-5 lg:flex-row lg:items-center lg:justify-between">
              <div>
                <div className="text-base font-medium">{selectedResources.length} resources selected</div>
                <div className="text-sm text-muted-foreground">Estimated total size: {formatFileSize(selectedTotalBytes)}</div>
                {downloadError ? <div className="mt-1 text-sm text-destructive">{downloadError}</div> : null}
              </div>
              <div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap">
                <Button variant="ghost" onClick={() => setSelectedIds([])}>
                  Clear selection
                </Button>
                <Button variant="outline" onClick={copySelectedIds}>
                  {copied ? "Copied IDs" : "Copy selected IDs"}
                  <Copy className="h-4 w-4" />
                </Button>
                <Button variant="outline" onClick={handleSelectionDownload} disabled={downloadingSelection}>
                  {downloadingSelection ? "Preparing bundle…" : "Download selection"}
                  <Download className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
