// next-omnipath/src/features/explore/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { parseAsString, parseAsStringLiteral, useQueryState } from "nuqs";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useEntitySelection } from "@/contexts/entity-selection-context";
import { AnnotationBrowserTab } from "@/features/explore/components/annotation-browser-tab";
import { EntitiesExploreTab } from "@/features/explore/components/entities-explore-tab";
import { ExploreBrowserShell } from "@/features/explore/components/explore-browser-shell";
import { RelationsExploreTab } from "@/features/explore/components/relations-explore-tab";
import type { SearchFilters } from "@/types/search";

const exploreTabParser = parseAsStringLiteral(["entity", "relations", "ontology"] as const).withDefault("entity");
const speciesParser = parseAsString.withDefault("9606");
const queryParser = parseAsString.withDefault("");

const SPECIES_OPTIONS = [
  { value: "9606", label: "Human" },
  { value: "10090", label: "Mouse" },
  { value: "10116", label: "Rat" },
  { value: "7227", label: "Fruit fly" },
  { value: "6239", label: "C. elegans" },
  { value: "7955", label: "Zebrafish" },
] as const;

function buildSelectionHref(entityIds: string[], annotationIds: string[]) {
  const params = new URLSearchParams();
  if (entityIds.length > 0) params.set("entities", entityIds.join(","));
  if (annotationIds.length > 0) params.set("annotations", annotationIds.join(","));
  return `/selection${params.toString() ? `?${params.toString()}` : ""}`;
}

export default function ExplorePage() {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement | null>(null);
  const [tab, setTab] = useQueryState("tab", exploreTabParser);
  const [query, setQuery] = useQueryState("q", queryParser);
  const [species, setSpecies] = useQueryState("species", speciesParser);
  const [draftQuery, setDraftQuery] = useState(query);
  const [entityFilters, setEntityFilters] = useState<SearchFilters>({ ncbi_tax_id: [species || "9606"] });
  const [interactionFilters, setInteractionFilters] = useState<SearchFilters>({});
  const { entityIds, annotationIds, totalSelectionCount } = useEntitySelection();

  useEffect(() => {
    setDraftQuery(query);
  }, [query]);

  useEffect(() => {
    setEntityFilters((prev) => ({
      ...prev,
      ncbi_tax_id: species ? [species] : ["9606"],
    }));
  }, [species]);

  const submitSearch = useCallback(() => {
    void setQuery(draftQuery.trim() || null);
  }, [draftQuery, setQuery]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      const tagName = target?.tagName;
      const isTypingTarget = tagName === "INPUT" || tagName === "TEXTAREA" || tagName === "SELECT" || target?.isContentEditable;

      if (event.key === "/" && !isTypingTarget) {
        event.preventDefault();
        inputRef.current?.focus();
        inputRef.current?.select();
        return;
      }

      if ((event.key === "s" || event.key === "S") && !isTypingTarget && totalSelectionCount > 0) {
        event.preventDefault();
        router.push(buildSelectionHref(entityIds, annotationIds));
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [annotationIds, entityIds, router, totalSelectionCount]);

  const selectionHref = useMemo(() => buildSelectionHref(entityIds, annotationIds), [annotationIds, entityIds]);

  const content = tab === "entity"
    ? (
      <EntitiesExploreTab
        query={query}
        species={species || "9606"}
        filters={entityFilters}
        onFiltersChange={setEntityFilters}
      />
    ) : tab === "relations"
      ? (
        <RelationsExploreTab
          filters={interactionFilters}
          onFilterChange={setInteractionFilters}
          useInternalRefineLayout={false}
        />
      ) : (
        <AnnotationBrowserTab query={query} species={species || "9606"} />
      );

  return (
    <ExploreBrowserShell
      query={query}
      draftQuery={draftQuery}
      onDraftQueryChange={setDraftQuery}
      onSubmitSearch={submitSearch}
      tab={tab}
      onTabChange={(next) => void setTab(next)}
      tabs={[
        { value: "entity", label: "entity" },
        { value: "relations", label: "relations" },
        { value: "ontology", label: "ontology" },
      ]}
      content={content}
      searchPlaceholder={tab === "ontology" ? "Search ontology terms…" : tab === "relations" ? "Search relations…" : "Search entities…"}
      searchInputRef={inputRef}
      species={species}
      onSpeciesChange={(value) => void setSpecies(value)}
      showSpeciesPicker={tab === "entity"}
      speciesOptions={SPECIES_OPTIONS}
      footerCta={totalSelectionCount > 0 ? (
        <Button asChild size="lg" className="fixed bottom-6 right-6 z-40 h-12 rounded-full px-4 shadow-lg">
          <Link href={selectionHref} className="flex items-center gap-2">
            <span>Open Selection</span>
            <Badge variant="secondary" className="rounded-full px-2 py-0.5 text-xs">
              {totalSelectionCount}
            </Badge>
            <ArrowRight className="size-4" />
          </Link>
        </Button>
      ) : null}
    />
  );
}

// omnipath-svelte/src/routes/explore/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { browser } from '$app/environment';
	import { ArrowRight } from '@lucide/svelte';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import ExploreBrowserShell from '$lib/components/explore/ExploreBrowserShell.svelte';
	import EntitiesExploreTab from '$lib/components/explore/EntitiesExploreTab.svelte';
	import RelationsExploreTab from '$lib/components/explore/RelationsExploreTab.svelte';
	import AnnotationBrowserTab from '$lib/components/explore/AnnotationBrowserTab.svelte';
	import { getSelectionStore } from '$lib/stores/selection.svelte';
	import type { SearchFilters } from '$lib/types/search';

	const SPECIES_OPTIONS = [
		{ value: '9606', label: 'Human' },
		{ value: '10090', label: 'Mouse' },
		{ value: '10116', label: 'Rat' },
		{ value: '7227', label: 'Fruit fly' },
		{ value: '6239', label: 'C. elegans' },
		{ value: '7955', label: 'Zebrafish' }
	] as const;

	const selection = getSelectionStore();

	let inputRef = $state<HTMLInputElement | null>(null);
	let draftQuery = $state('');
	let entityFilters = $state<SearchFilters>({ ncbi_tax_id: ['9606'] });
	let interactionFilters = $state<SearchFilters>({});
	let annotationFilters = $state<SearchFilters>({});

	const tab = $derived($page.url.searchParams.get('tab') || 'entity');
	const query = $derived($page.url.searchParams.get('q') || '');
	const species = $derived($page.url.searchParams.get('species') || '9606');

	$effect(() => {
		draftQuery = query;
	});

	function setTab(next: string) {
		const url = new URL($page.url);
		url.searchParams.set('tab', next);
		goto(url, { replaceState: true, keepFocus: true, noScroll: true });
	}

	function setQuery(next: string) {
		const url = new URL($page.url);
		if (next.trim()) {
			url.searchParams.set('q', next.trim());
		} else {
			url.searchParams.delete('q');
		}
		goto(url, { replaceState: true, keepFocus: true, noScroll: true });
	}

	function setSpecies(value: string | null) {
		const url = new URL($page.url);
		if (value) {
			url.searchParams.set('species', value);
		} else {
			url.searchParams.delete('species');
		}
		goto(url, { replaceState: true, keepFocus: true, noScroll: true });
	}

	function submitSearch() {
		setQuery(draftQuery);
	}

	function buildSelectionHref(entityIds: string[], annotationIds: string[]) {
		const params = new URLSearchParams();
		if (entityIds.length > 0) params.set('entities', entityIds.join(','));
		if (annotationIds.length > 0) params.set('annotations', annotationIds.join(','));
		return `/selection${params.toString() ? `?${params.toString()}` : ''}`;
	}

	$effect(() => {
		if (!browser) return;
		const onKeyDown = (event: KeyboardEvent) => {
			const target = event.target as HTMLElement | null;
			const tagName = target?.tagName;
			const isTypingTarget =
				tagName === 'INPUT' || tagName === 'TEXTAREA' || tagName === 'SELECT' || target?.isContentEditable;

			if (event.key === '/' && !isTypingTarget) {
				event.preventDefault();
				inputRef?.focus();
				inputRef?.select();
				return;
			}

			if ((event.key === 's' || event.key === 'S') && !isTypingTarget && selection.totalSelectionCount > 0) {
				event.preventDefault();
				goto(buildSelectionHref(selection.entityIds, selection.annotationIds));
			}
		};

		window.addEventListener('keydown', onKeyDown);
		return () => window.removeEventListener('keydown', onKeyDown);
	});

	const selectionHref = $derived(buildSelectionHref(selection.entityIds, selection.annotationIds));

	const searchPlaceholder = $derived(
		tab === 'ontology' ? 'Search ontology terms…' : tab === 'relations' ? 'Search relations…' : 'Search entities…'
	);
</script>

<svelte:window />

<ExploreBrowserShell
	{query}
	{draftQuery}
	onDraftQueryChange={(value) => (draftQuery = value)}
	onSubmitSearch={submitSearch}
	{tab}
	onTabChange={setTab}
	tabs={[
		{ value: 'entity', label: 'entity' },
		{ value: 'relations', label: 'relations' },
		{ value: 'ontology', label: 'ontology' }
	]}
	searchPlaceholder={searchPlaceholder}
	bind:searchInputRef={inputRef}
	{species}
	onSpeciesChange={setSpecies}
	showSpeciesPicker={tab === 'entity'}
	speciesOptions={SPECIES_OPTIONS}
>
	{#snippet content()}
		{#if tab === 'entity'}
			<EntitiesExploreTab {query} {species} filters={entityFilters} onFiltersChange={(f) => (entityFilters = f)} />
		{:else if tab === 'relations'}
			<RelationsExploreTab filters={interactionFilters} onFilterChange={(f) => (interactionFilters = f)} />
		{:else}
			<AnnotationBrowserTab {query} {species} filters={annotationFilters} onFiltersChange={(f) => (annotationFilters = f)} />
		{/if}
	{/snippet}

	{#snippet footerCta()}
		{#if selection.totalSelectionCount > 0}
			<Button
				href={selectionHref}
				size="lg"
				class="fixed bottom-6 right-6 z-40 h-12 rounded-full px-4 shadow-lg"
			>
				<span class="flex items-center gap-2">
					<span>Open Selection</span>
					<Badge variant="secondary" class="rounded-full px-2 py-0.5 text-xs">
						{selection.totalSelectionCount}
					</Badge>
					<ArrowRight class="size-4" />
				</span>
			</Button>
		{/if}
	{/snippet}
</ExploreBrowserShell>
