// omnipath-svelte/src/lib/components/interactions/InteractionDetailsSheet.svelte
<script lang="ts">
  import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '$lib/components/ui/sheet/index.js';
  import InteractionDetails from './InteractionDetails.svelte';
  import { fetchRelationEvidence } from '$lib/api/client';
  import type { InteractionDetailsData, InteractionListRow } from '$lib/types/interactions';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    interaction: InteractionListRow | null;
  }

  let { open, onOpenChange, interaction }: Props = $props();

  let evidence = $state<InteractionDetailsData['evidence']>([]);
  let evidenceLoading = $state(false);
  let evidenceError = $state<string | null>(null);

  const relationPk = $derived(interaction?.relation.relationPk);

  $effect(() => {
    if (!open || !relationPk) return;
    evidenceLoading = true;
    evidenceError = null;
    fetchRelationEvidence(relationPk)
      .then((data) => {
        evidence = data.evidence;
      })
      .catch((err) => {
        evidenceError = err instanceof Error ? err.message : 'Failed to load evidence';
      })
      .finally(() => {
        evidenceLoading = false;
      });
  });

  const details = $derived<InteractionDetailsData | InteractionListRow | null>(
    interaction ? { ...interaction, evidence } : null
  );
</script>

<Sheet {open} onOpenChange={onOpenChange}>
  <SheetContent class="w-full overflow-y-auto pb-8 sm:max-w-2xl">
    <SheetHeader>
      <SheetTitle>Relation Details</SheetTitle>
      <SheetDescription>View relation metadata and evidence for this record</SheetDescription>
    </SheetHeader>

    <div class="mb-6 mt-6">
      {#if evidenceError}
        <div class="p-4 text-sm text-destructive">{evidenceError}</div>
      {:else}
        <InteractionDetails selectedInteraction={details} {evidenceLoading} />
      {/if}
    </div>
  </SheetContent>
</Sheet>

// next-omnipath/src/features/interactions-search/components/interaction-details-sheet.tsx
"use client"

import { useQuery } from "@tanstack/react-query"
import { useEffect, useMemo, useState } from "react"
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet"
import { InteractionDetails } from "@/features/interactions-search/components/interaction-details"
import type { InteractionDetailsData, InteractionListRow } from "@/features/interactions-search/types"

interface InteractionDetailsSheetProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  interaction: InteractionListRow | null
}

export function InteractionDetailsSheet({ open, onOpenChange, interaction }: InteractionDetailsSheetProps) {
  const [resolvedInteraction, setResolvedInteraction] = useState<InteractionListRow | null>(interaction)

  useEffect(() => {
    setResolvedInteraction(interaction)
  }, [interaction])

  const interactionId = interaction?.interaction.interactionPk

  const { data: details, isLoading } = useQuery({
    queryKey: ["interaction-details", interactionId],
    enabled: open && !!interactionId,
    staleTime: 5 * 60 * 1000,
    queryFn: async () => {
      const response = await fetch(`/api/interactions/${interactionId}`)
      if (!response.ok) {
        throw new Error(`Failed to load interaction details (${response.status})`)
      }
      return await response.json() as InteractionDetailsData | null
    },
  })

  const displayInteraction = useMemo(() => {
    if (details) return details
    return resolvedInteraction
  }, [details, resolvedInteraction])

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-2xl overflow-y-auto pb-8">
        <SheetHeader>
          <SheetTitle>Interaction Details</SheetTitle>
          <SheetDescription>
            View detailed evidence for this interaction
          </SheetDescription>
        </SheetHeader>

        <div className="mt-6 mb-6">
          {isLoading && !details ? (
            <div className="p-4 text-sm text-muted-foreground">Loading evidence…</div>
          ) : (
            <InteractionDetails selectedInteraction={displayInteraction} />
          )}
        </div>
      </SheetContent>
    </Sheet>
  )
}
